### ISSUE TITLE
`ignore_http_errors` should be named `ignore_https_errors` to mirror `ignoreHTTPSErrors`

### ISSUE THREAD

**Issue by Boscop** [octaltree/playwright-rust#10]
https://github.com/octaltree/playwright-rust/search?q=ignoreHTTPSErrors

`ignore_http_errors` should be named `ignore_https_errors`, (because it's about HTTPS), and mirrors `ignoreHTTPSErrors` :)

At first I thought `ignoreHTTPSErrors` is not supported because I thought `ignore_http_errors` means something else.

**Comment by octaltree** [comment]
Thanks for the bug report.
