### ISSUE TITLE
generate HAR data?

### ISSUE THREAD

**Issue by initprism** [octaltree/playwright-rust#12]
I wonder how to detect page, network events to generate HAR.

**Comment by octaltree** [comment]
Are you looking for [`playwright::api::browser::ContextBuilder::record_har`](https://docs.rs/playwright/0.0.5/playwright/api/browser/struct.ContextBuilder.html#method.record_har) or [`playwright::api::browser_type::PersistentContextLauncher::record_har`](https://docs.rs/playwright/0.0.5/playwright/api/browser_type/struct.PersistentContextLauncher.html#method.record_har)?
Playwright doesn't provide "Save each network event as HAR".
https://playwright.dev/docs/api/class-response
