### ISSUE TITLE
Features are supposed to be additive

### ISSUE THREAD

**Issue by nox** [octaltree/playwright-rust#8]
Crate features are supposed to be additive, it should be possible to enable multiple runtimes at once.

**Comment by octaltree** [comment]
The selectivity runtime is taken from [launchbadge/sqlx](https://github.com/launchbadge/sqlx). Only one runtime can be selected in sqlx.
It is possible to not include any runtime as default, as sqlx does, but tokio is the de facto standard and you should add `default-features=false` to use other runtimes.

**Comment by octaltree** [comment]
I have not read any documentation on features design. What should be avoided more, `default-feature=false` or must-select-to-work?
