### ISSUE TITLE
How to only install one browser?

### ISSUE THREAD

**Issue by Boscop** [octaltree/playwright-rust#9]
Thanks for this useful crate :)

I have a question:
How to only install one browser? (E.g. chromium)

**Comment by octaltree** [comment]
Glad to see you're using this.

You can use this snippet.
```rust
fn install_chromium(playwright: &mut Playwright) -> std::io::Result<()>{
  std::process::Command::new(playwright.driver().executable())
    .args(&["install", "chrome"])
    .status()?
  Ok(())
}
```
I may provide this from playwright-rust later.
